name: Node.js CI

on:
  pull_request:
    paths-ignore:
      - "*.md"
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["12", "14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: yarn --frozen-lockfile
      - run: npm test
      - run: bash <(curl -s https://codecov.io/bash)
